// Copyright (c) 2019 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:projectid: cloud-azure
:page-layout: guide-multipane
:page-duration: 15 minutes
:page-releasedate: 2019-08-01
:page-description: Learn how to deploy microservices to Azure Kubernetes Service (AKS).
:page-tags: ['Docker']
:page-permalink: /guides/{projectid}
:page-related-guides: ['docker', 'kubernetes-intro']
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:source-highlighter: prettify
:page-seo-title: Deploying microservices to Azure Kubernetes Service
:page-seo-description: Find out how to deploy an app to Azure Kubernetes Service
:page-guide-category: microprofile
:guide-author: Open Liberty
= Deploying microservices to Azure Kubernetes Service

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form,
view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].

Learn how to deploy your microservices application to Azure Kubernetes Service (AKS).

:kube: Kubernetes
:hashtag: #
:win: WINDOWS
:mac: MAC
:linux: LINUX
:system-api: http://[hostname]:9080/system/properties
:inventory-api: http://[hostname]:9081/inventory/systems


// =================================================================================================
// Introduction
// =================================================================================================

== What you'll learn

You will learn how to deploy two microservices in Open Liberty containers to a {kube} cluster on
Azure Kubernetes Service (AKS).

Kubernetes is an open source container orchestrator that automates many tasks involved in 
deploying, managing, and scaling containerized applications. If you would like to learn
more about Kubernetes, check out the https://openliberty.io/guides/kubernetes-intro.html[Deploying microservices to Kubernetes^]
guide.

There are different cloud-based solutions for running your workloads in a {kube} cluster. 
A cloud-based infrastructure enables you to focus on developing your microservices without 
worrying about details related to the servers you deploy them to. Using a cloud helps 
you to easily scale and serve your microservices in a high-availability setup.

Azure offers a managed {kube} service called Azure Kubernetes Service (AKS). AKS simplifies the process of running Kubernetes on Azure without 
needing to install or maintain your own Kubernetes control plane. It provides a hosted {kube} 
cluster that you can deploy your microservices to. You will use AKS with an Azure
Container Registry (ACR). ACR is a private registry that is used to store 
and distribute your container images. Note, since AKS is not free, there is a small
cost that is associated with deployig this application. See the official
https://azure.microsoft.com/en-us/pricing/details/kubernetes-service/[AKS pricing^] documentation for more details.

The two microservices that you'll be working with are called `system` and `inventory`. 
The `system` microservice returns the JVM system properties of the running container.  
The `inventory` microservice adds the properties from the `system` microservice to the inventory. 
This guide demonstrates how both microservices can run and communicate
in different isolated containers.

// =================================================================================================
// Prerequisites
// =================================================================================================

== Prerequisites

Before you begin, the following tools need to be installed:

- *Docker:* You need a containerization software for building containers. Kubernetes 
supports various container types, but you will use Docker in this guide. For installation 
instructions, refer to the official https://docs.docker.com/install/[Docker^] documentation.

- *Azure Subscription:* To run this guide, you will need an Azure subscription. Navigate to the 
https://azure.microsoft.com/en-us/pricing/purchase-options/pay-as-you-go/[Microsoft Azure Purchase Options] 
to create an account with your email and start a Pay-As-You-Go subscription. 

- *Azure CLI:* You will need to use the Azure Command Line Interface (CLI). See the official
https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest[Install the Azure CLI^]
documentation for information about setting up the Azure CLI for your platform.

    To verify that the Azure CLI is installed correctly, run the following command:
    
    [role=command]
    ```
    az --version
    ```

- *kubectl:* You need the Kubernetes command-line tool `kubectl` to interact with your Kubernetes cluster.
Use the Azure CLI to download and install `kubectl` with the following command:

    [role=command]
    ```
    az aks install-cli
    ```

To begin this guide, make sure that you are logged in to Azure to get access to your subscription:

[role=command]
```
az login
```

// =================================================================================================
// Getting started
// =================================================================================================

[role=command]
include::{common-includes}/gitclone.adoc[]

// no "try what you'll build" section in this guide since it would be too long due to all setup the user will have to do.

// =================================================================================================
// Managing an Azure Container Registry
// =================================================================================================

== Managing an Azure Container Registry

In order to deploy your microservices, you need to create an Azure Container Registry in the same location
as where your services will be deployed. 

=== Creating a resource group

Your Azure Container Registry will be placed inside its own resource group that you will create.

A resource group is a logical collection of related resources that can be deployed and maintained as a single entity.
For instance, virtual machines, databases, and storage networks are types of resources that resource groups can be formed from.
Resource groups are dedicated to container registries because the resources in these registries are used by several 
different hosts and their containers. 

To create a resource group, an Azure location must be specified. The metadata for your resources are stored at this given location. 
If resources are created without specifying a location and created after creating a resource group, these new resources will run in the
same region specfied by the resource group location. 

See the list of available Azure regions for your Azure subscription:

[role=command]
```
az account list-locations -o table
```

The `name` column specifies the region name that you will be using to create your resource group


You will see an output similar to the following:

[source, role="no_copy"]
----
DisplayName          Latitude    Longitude    Name
-------------------  ----------  -----------  ------------------
Central US           41.5908     -93.6208     centralus
East US              37.3719     -79.8164     eastus
East US 2            36.6681     -78.3889     eastus2
West US              37.783      -122.417     westus
North Central US     41.8819     -87.6278     northcentralus
South Central US     29.4167     -98.5        southcentralus
Canada Central       43.653      -79.383      canadacentral
Canada East          46.817      -71.217      canadaeast
UK South             50.941      -0.799       uksouth
UK West              53.427      -3.084       ukwest
West Central US      40.890      -110.234     westcentralus
West US 2            47.233      -119.852     westus2
----

However, AKS is not available in all regions. Make sure that the region you select is 
https://azure.microsoft.com/en-us/global-infrastructure/services/?products=kubernetes-service[compatible with AKS^].

Create a resource group and replace `[location]` with a region that is available for your subscription and compatible with AKS.

[role=command]
```
az group create -l [location] -n guide-group
```

You will see an output similar to the following:

[source, role="no_copy"]
```
{
  "id": "/subscriptions/[subscription-id]/resourceGroups/guide-group",
  "location": "[location]",
  "managedBy": null,
  "name": "guide-group",
  "properties": {
    "provisioningState": "Succeeded"
  },
  "tags": null,
  "type": null
}
```

=== Creating a container registry

Your private container registry will manage Docker images that you will build in later steps. 
With the Azure `az acr` command, create an Azure Container Registry.

[role=command]
```
az acr create -g guide-group -n guide-registry --sku Basic --admin-enabled
```

You will see an output similar to the following:

[role="no_copy"]
```
{
  "adminUserEnabled": true,
  "creationDate": "2019-06-05T20:28:09.637994+00:00",
  "id": "/subscriptions/[subscription-id]/resourceGroups/guide-group/providers/Microsoft.ContainerRegistry/registries/guide-registry",
  "location": "[location]",
  "loginServer": "guide-registry.azurecr.io",
  "name": "guide-registry",
  "networkRuleSet": null,
  "provisioningState": "Succeeded",
  "resourceGroup": "guide-group",
  "sku": {
    "name": "Basic",
    "tier": "Basic"
  },
  "status": null,
  "storageAccount": null,
  "tags": {},
  "type": "Microsoft.ContainerRegistry/registries"
}
```

In the `az acr create` command, the `-g` option specifies the resource group to designate to the container registry. 
You created this resource group before as `guide-group`. The `-n` option specifies the name of the
container registry to be created, which was defined as `guide-registry`. The `--admin-enabled` flag indicates that the admin user is enabled. 

The possible Stock Keeping Unit (SKU) values that can be passed into the `--sku` option are `Basic`, `Standard`, and `Premium`.
These different SKU options provide pricing for various levels of capacity and usage. Since your application involves a lower usage of
storage and image throughput, you are using a `Basic` SKU, due to its cost-optimized solution. 

Your container registry has a server name of `guide-registry.azurecr.io`. 

=== Logging into the container registry

You must log into your Azure Container Registry using the Azure CLI, in order to be able to push Docker images to your registry.

[role=command]
```
az acr login -n guide-registry
```

Once you login, you will see the following:

[role="no_copy"]
----
Login Succeeded
----

Your login credentials will be needed later, so keep your given password in mind. 

[role=command]
```
az acr credential show -n guide-registry
```

You will see an output similar to the following:

[role="no_copy"]
```
{
  "passwords": [
    {
      "name": "password",
      "value": "[password]"
    },
  ],
  "username": "guide-registry"
}
```

// =================================================================================================
// Uploading images to a container registry
// =================================================================================================

=== Building your Docker images

The starting Java project, which you can find in the `start` directory, is a multi-module Maven
project. It is made up of the `system` and `inventory` microservices. Each microservice resides in its own directory,
`start/system` and `start/inventory`. Both of these directories contain a Dockerfile, which is necessary
for building the Docker images.

Navigate to the `start` directory and run the following command:

[role=command]
```
mvn install
```

Now that your microservices are packaged, you will build your 
Docker images using the `docker build` command. To build your image, you need to have Docker installed 
and your Docker daemon started.

Run the following commands to build and containerize the application:

[role='command']
```
docker build -t system system/.
docker build -t inventory inventory/.
```

To verify that the images are built, run the `docker images` command to list all local Docker images:

[role='command']
```
docker images
```

Your two images `inventory` and `system` should appear in the list of all Docker images:

[role="no_copy"]
----
REPOSITORY    TAG       IMAGE ID        CREATED          SIZE
inventory     latest    08fef024e986    4 minutes ago    471MB
system        latest    1dff6d0b4f31    5 minutes ago    470MB
----

=== Pushing the images to a container registry

Pushing the images to a registry allows the cluster to create pods by using your container images.

Tag your container images with your registry:

[role=command]
```
docker tag inventory:latest guide-registry.azurecr.io/inventory
docker tag system:latest guide-registry.azurecr.io/system
```

Finally, push your images to the registry:

[role=command]
```
docker push guide-registry.azurecr.io/inventory
docker push guide-registry.azurecr.io/system
```

// =================================================================================================
// Creating a Kubernetes cluster on AKS
// =================================================================================================

== Creating a Kubernetes cluster on AKS

=== Provisioning a cluster

To create your AKS cluster, use the `az aks create` cluster command:

[role=command]
```
az aks create -g guide-group --name guide-cluster --generate-ssh-keys
```

Running this command creates an AKS cluster that is called `guide-cluster` with the resource group
`guide-group`. The `--generate-ssh-keys` option creates `SSH` key files, if they are missing,
and then stores them in the `~/.ssh` directory.

The option `--node-count -c` could also be added to this `az aks create` command to create a cluster
with a certain number of nodes in the Kubernetes node pool. By default, if this option is excluded,
3 nodes will be assigned to the node pool.

An AKS cluster requires a service principal, which is a security credential that allows you to assign specific permissions
for Azure resources accessed by applications and services. The `az aks create` command automatically generates a service principal to use 
with your newly created cluster. However, in order to run this command, your Azure account must have permission access to create
service principals. 

Service principals can also be created manually. 


Once the cluster is created, the command outputs information about the cluster.



// =================================================================================================
// Tear Down
// =================================================================================================

== Tearing down the environment


// =================================================================================================
// finish
// =================================================================================================

== Great work! You're done!
